# Generated by Django 4.0.4 on 2022-05-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='carousel')),
                ('bg_color', models.CharField(default='#ffffff', max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('link_to', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
