# Generated by Django 4.0.4 on 2022-05-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_color_product_id_product_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(related_name='colors', to='app.color'),
        ),
    ]
