# Generated by Django 4.0.4 on 2022-05-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_orderitem_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_uuid',
        ),
    ]
