# Generated by Django 4.0.4 on 2022-05-31 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_order_order_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
