# Generated by Django 4.0.4 on 2022-05-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_orderitem_color_remove_product_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
