# Generated by Django 4.0.4 on 2022-05-31 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shippingPrice',
        ),
    ]
