# Generated by Django 4.0.4 on 2022-05-31 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_order_delivery_choice_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
