# Generated by Django 4.0.4 on 2022-05-31 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_order_paid_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='profile_pic',
            new_name='image',
        ),
    ]
