# Generated by Django 4.0.4 on 2022-05-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_profile_pic_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, default='users/profilepic.jpg', null=True, upload_to='users/<built-in function id>'),
        ),
    ]
