# Generated by Django 4.0.4 on 2022-09-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_coupon_alter_account_image_order_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_fullname', models.CharField(max_length=60)),
                ('sender_address', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('sender_phone', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sender_email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('package_detail', models.CharField(max_length=60)),
                ('package_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approximate_distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receiver_fullname', models.CharField(max_length=60)),
                ('receiver_address', models.CharField(max_length=60)),
                ('receiver_phone', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receiver_email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
            ],
        ),
    ]
