# Generated by Django 4.1.1 on 2022-09-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_address_user_id_trackingnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingnumber',
            name='status',
            field=models.CharField(choices=[('Item is ready to be dispatched.', 'Item is ready to be dispatched.'), ('Carrier picked up the package.', 'Carrier picked up the package.'), ('Package arrived at a carrier facility.', 'Package arrived at a carrier facility.'), ('Out for delivery.', 'Out for delivery.'), ('Carrier is unable to gain access to the front door. Please contact Estorage to provide additional information', 'Carrier is unable to gain access to the front door. Please contact Estorage to provide additional information'), ('Carrier delivered the package.', 'Carrier delivered the package.')], default=('Item is ready to be dispatched.', 'Item is ready to be dispatched.'), max_length=255),
        ),
    ]
