# Generated by Django 4.1.1 on 2022-09-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_alter_trackingnumber_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=60)),
                ("lastname", models.CharField(max_length=60)),
                ("phone", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "email",
                    models.EmailField(max_length=60, unique=True, verbose_name="email"),
                ),
                ("message", models.CharField(max_length=60)),
            ],
        ),
    ]
